version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=${DB_USERNAME}
      - MONGO_PASSWORD=${DB_PASSWORD}
    command: npm run dev