version: "3"
services:
  node-app:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:${PORT}"
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=obinna
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis

volumes:
  mongo_db: