version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=obinna
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis

volumes:
  mongo_db: