version: '3'
services:
  nginx:
    ports:
      - "3000:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file:
      - ./.env
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=${DB_USERNAME}
      - MONGO_PASSWORD=${DB_PASSWORD}
      - SESSION_SECRET=secret
    command: npm run dev
  
  mongo:
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}