version: "3"
services:
  node-app:
    build: .
    env_file:
      - ./.env
    ports:
      - "3000:${PORT}"

  mongo:
    image: mongo
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: