version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    image: 19991057823/node-app-wkflow
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - mongo_db:/data/db

  redis:
    image: redis

volumes:
  mongo_db: